### ISSUE TITLE
RFC: Add check percentage override field

### ISSUE THREAD

**Issue by TimJentzsch** [GrafeasGroup/blossom#303]
The percentages to determine if a transcription should be reviewed are currently determined automatically by Blossom, based on the user's total gamma.

For some users it might be necessary to monitor them more closely for a longer time, if they are having trouble with the formatting.
The welcome and user teams have been requesting a feature to manually mark a user to generate more checks.

To accomplish this, I recommend a database field to override the check percentage for a given user.
Slack commands should be added to set and clear this field as needed.

## Database models:

Add a new field to the `BlossomUser` model:
- `override_check_factor: Optional[float]` The new decimal value to use as a percentage for the transcription checks. Must be a value between `0` and `1`. If it is `None`, the automatic algorithm is used. Defaults to `None`.

## Slack commands:

Add two new Slack commands (probably to the Blossom bot):
- `watch <username> <optional_factor>` Sets a new factor for a given user. The factor must be a value between `0` and `1`, defaulting to `1`.
- `unwatch <username>` Sets the `override_check_factor` back to `None`.

If a check has been generated with an overridden factor, it should be reflected in the review message.

**Comment by itsthejoker** [comment]
I love it! The only suggestion I have is to change the `optional_factor` to be a percentage so that the non-technical people feel more comfortable with it -- it's easier to think "70%" than it is to remember to type 0.7, and we can easily correct for that on the backend.

**Comment by TimJentzsch** [comment]
That's a good suggestion, makes sense!
