### ISSUE TITLE
Add `subinfo` Slack command

### ISSUE THREAD

**Issue by TimJentzsch** [GrafeasGroup/blossom#495]
Add a new command to Slack that allows you to get info about a given subreddit.

Usage: `@Blossom subinfo <subreddit_name>`

It could contain the following info:

- Total posts in the queue (and percentage of all subs)
- Current posts in the queue (and percentage of all subs)
- Total transcriptions (and percentage of all subs, percentage of in queue)
- Total volunteers transcribing that sub

**Comment by itsthejoker** [comment]
I was literally thinking about this just a few minutes ago. Are you planning on tackling it or should I take a look tonight?

**Comment by TimJentzsch** [comment]
I'm already on it :)
