### ISSUE TITLE
Notify Welcome team if a person unclaims their CoC post and then claims another

### ISSUE THREAD

**Issue by Altrissa** [GrafeasGroup/blossom#84]
Right now, a user can claim their first post, accept the CoC, and then unclaim the post. When that happens, we don't get a notification on their next claim so they aren't properly vetted or welcomed. If a user claims a post and their CoC acceptance is true but gamma is null, a notification to Slack to track their first transcription would be helpful.

**Comment by itsthejoker** [comment]
This issue is resolved by https://github.com/GrafeasGroup/blossom/pull/136
